# Generated by Django 3.2.16 on 2023-01-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[('Easiest', 'E'), ('Moderate', 'M'), ('Moderately Strenous', 'MS'), ('Strenous', 'S'), ('Very Strenous', 'VS')], default='Difficulty Level', max_length=20, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, default='Excerpt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Title', max_length=200, unique=True),
        ),
    ]
